#!/bin/bash -x

# DEPENDENCIES
# curl - for downloading files (alternative might be wget)
# feh - for setting a wallpaper (can use nitrogen as well or others)
# xorg-xrandr - for figuring out screen resolution (instead of hardcoding)
# imagemagick - for branding

# String: random | buildings | food | nature | people | technology | objects
CATEGORY=random
# Int(seconds): 300+ / 5min+
TIMEOUT=300
# String: --bg-center | --bg-fill | --bg-scale | --bg-max | --bg-tile
BG_TYPE=--bg-fill
# Will contain something like 1600x900
RESOLUTION=$(xrandr -q | grep -oP '(?<=connected )(\d+x\d+)' --color=auto)
# The position of the branding logo:
# NorthWest | North | NorthEast | West | Center | East | SouthWest | South | SouthEast
BRAND_POSITION=SouthEast
# Default wallpaper path
DEFAULT_WALLPAPER=~/Pictures/wall.jpg

function getScriptDir() {
  local SOURCE="${BASH_SOURCE[0]}"
  while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    local DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    local SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && local SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  done
  local DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo $DIR
}

SCRIPT_DIR=$(getScriptDir)

function setWallpaper () {
  # download new image
  curl -L https://source.unsplash.com/$CATEGORY/$RESOLUTION > ~/tmp/unpaper.jpg
  # add branding
  composite -gravity $BRAND_POSITION "$SCRIPT_DIR/brand_logo.png" ~/tmp/unpaper.jpg ./unpaper_branded.jpg
  # set wallpaper
  feh $BG_TYPE ~/tmp/unpaper_branded.jpg
  # if fail, set defaultwallpaper
  if [[ $? != 0 ]]; then
    feh $BG_TYPE $DEFAULT_WALLPAPER
  fi
}

if [[ $* == *-d* ]]; then
  while [[ true ]]; do
    setWallpaper
    sleep $TIMEOUT
  done
else
  setWallpaper
fi
